version: '3.8'

services:
  node:
    image: node:18
    volumes:
      - .:/home/app:delegated
      - node_modules:/home/app/node_modules
    working_dir: /home/app
    ports:
      - "3000:3000"
    tty: true

volumes:
 node_modules:
